[".config/zsh/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-history-substring-search"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-history-substring-search.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-vi-mode"]
    type = "git-repo"
    url = "https://github.com/jeffreytse/zsh-vi-mode.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-defer"]
    type = "git-repo"
    url = "https://github.com/romkatv/zsh-defer.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/zenlian/nvim.git"
